# Generated by Django 5.0.9 on 2024-11-03 15:23

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_rate', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('number_of_ratings', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_id', models.CharField(blank=True, max_length=255, null=True)),
                ('recipe_name', models.CharField(max_length=1000, validators=[django.core.validators.MinLengthValidator(5)])),
                ('type_of_meal', models.CharField(choices=[('Śniadanie', 'Śniadanie'), ('Obiad', 'Obiad'), ('Kolacja', 'Kolacja')], max_length=255)),
                ('ingredients', models.TextField(validators=[django.core.validators.MinLengthValidator(10)])),
                ('preparation', models.TextField(validators=[django.core.validators.MinLengthValidator(10)])),
                ('difficulty_level', models.CharField(choices=[('Łatwa', 'Łatwa'), ('Średnia', 'Średnia'), ('Trudna', 'Trudna')], max_length=10)),
                ('preparation_time', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('quantity_of_servings', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('energy_value_kcal', models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(0)])),
                ('protein_g', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('fat_g', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('carbohydrates_g', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('lactose_free', models.CharField(blank=True, max_length=255, null=True)),
                ('gluten_free', models.CharField(blank=True, max_length=255, null=True)),
                ('dairy_free', models.CharField(blank=True, max_length=255, null=True)),
                ('vegetarian_or_vegan', models.CharField(blank=True, max_length=255, null=True)),
                ('meat', models.CharField(blank=True, max_length=255, null=True)),
                ('fish', models.CharField(blank=True, max_length=255, null=True)),
                ('category', models.CharField(blank=True, choices=[('Wegetariańskie', 'Wegetariańskie'), ('Wegańskie', 'Wegańskie'), ('Mięsne', 'Mięsne'), ('Rybne', 'Rybne')], max_length=255, null=True)),
                ('images', models.URLField(blank=True, max_length=1000, null=True)),
                ('owner', models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('statistics', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='recipe.recipestatistics')),
            ],
        ),
    ]
